@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
{
    "name": "Vinicius Lopes",
    "email": "visepol@email.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json
{
    "name": "Vinicius Lopes",
    "email": "visepol@email.com",
    "password": "123456"
}

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
{
    "title": "Qual a cor do cavalo branco de Napoleão?",
    "content": "A pergunta é simples, qual a cor do cavalo branco de Napoleão?"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
